---
- hosts: serv1
  become: true
  remote_user: root
  tasks:
  
  
  
  - name: Установить authorized key из файла id_rsa.pub
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"